"""Evaluation on held-out splits — measured, never invented.

Produces metrics.json and confusion_matrix.png. The numbers in this repo's
README may only be quoted from these artefacts, generated by this module on a
held-out split.
"""
from __future__ import annotations

from pathlib import Path
from typing import Sequence

import numpy as np
import torch
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from torch.utils.data import DataLoader

from .utils import LatencyMeter, log, timed, write_json


def compute_metrics(
    model: torch.nn.Module,
    loader: DataLoader,
    classes: Sequence[str],
    device: str = "cpu",
) -> dict:
    """Run inference over a loader and return macro-F1, accuracy, p95 latency."""
    model.eval()
    y_true: list[int] = []
    y_pred: list[int] = []
    meter = LatencyMeter()

    with torch.no_grad():
        for x, y, _ in loader:
            x = x.to(device)
            with timed(meter):
                logits = model(x)
            y_true.extend(y.tolist())
            y_pred.extend(logits.argmax(dim=-1).cpu().tolist())

    if not y_true:
        return {"macro_f1": float("nan"), "accuracy": float("nan"), "p95_ms": float("nan")}

    return {
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "p95_ms": round(meter.p() * 1000.0, 2),
    }


def evaluate(
    model: torch.nn.Module,
    loader: DataLoader,
    classes: Sequence[str],
    device: str = "cpu",
    out_dir: str | Path = "logs",
    dataset_version: str = "unknown",
    model_version: str = "unknown",
    git_commit: str = "unknown",
) -> dict:
    """Evaluate and write metrics.json + confusion_matrix.png to ``out_dir``."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    model.eval()
    y_true, y_pred = [], []
    meter = LatencyMeter()
    with torch.no_grad():
        for x, y, _ in loader:
            x = x.to(device)
            with timed(meter):
                logits = model(x)
            y_true.extend(y.tolist())
            y_pred.extend(logits.argmax(dim=-1).cpu().tolist())

    metrics = {
        "model_version": model_version,
        "dataset_version": dataset_version,
        "git_commit": git_commit,
        "classes": len(classes),
        "macro_f1": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "p95_ms": round(meter.p() * 1000.0, 2),
    }
    write_json(out / "metrics.json", metrics)

    try:
        _write_confusion_matrix(y_true, y_pred, classes, out / "confusion_matrix.png")
    except Exception as exc:  # pragma: no cover - plotting is best-effort
        log.warning("confusion matrix render failed: %s", exc)

    log.info("evaluation: macro-F1 %.4f | acc %.4f | p95 %.2f ms",
             metrics["macro_f1"], metrics["accuracy"], metrics["p95_ms"])
    return metrics


def _write_confusion_matrix(y_true: list[int], y_pred: list[int],
                            classes: Sequence[str], path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    cm = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(max(6, len(classes) * 0.25), max(6, len(classes) * 0.25)))
    im = ax.imshow(cm, cmap="Blues")
    ax.set_xticks(np.arange(len(classes)), labels=classes, rotation=90, fontsize=6)
    ax.set_yticks(np.arange(len(classes)), labels=classes, fontsize=6)
    ax.set_xlabel("predicted")
    ax.set_ylabel("true")
    fig.colorbar(im)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
